name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: pull latest and remove old file from repo
        run: |
          git config --global user.name "usernamehere"
          git config --global user.email "emailhere"
          git config pull.rebase false
          git pull
          rm -f ResourcePack.zip
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: push changes to remote
        run: |
          python3 zip.py
          git add -A
          git commit -m "sha1: $(bash sha1.sh)"
          git push --force
