name: Create ResourcePack
on:
  push:
  schedule:
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: pull latest from repo
        run: |
          git config --global user.name "ResourcePack-Create"
          git config --global user.email "none"
          git config --global core.autocrlf true
          git config pull.rebase false
          git pull

      - name: push changes to remote
        run: |
          sha1=$(python3 zip.py)
          echo sha1: $sha1
          git add -A
          git commit -m "sha1: $sha1" || exit 0
          git push --force
