name: Create ResourcePack
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git config
        run: |
          git config --global user.name "ResourcePack-Create"
          git config --global user.email "none"
          git config --global core.autocrlf true

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Get latest release
        id: latest_release
        uses: actions/github-script@v4
        with:
          script: |
            const { data } = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return data;

      - name: Get asset hash
        id: asset_hash
        run: |
          curl -sLJO https://github.com/${{ github.repository }}/releases/download/${{ steps.latest_release.outputs.tag_name }}/ResourcePack.zip
          old_sha1=$(sha1sum ResourcePack.zip)
          echo old_sha1: $old_sha1


          new_sha1=$(python3 zip.py)
          echo new_sha1: $new_sha1
